### ISSUE TITLE
How to change Size of Lottie Animation 

### ISSUE THREAD

**Issue by AmanRaiAndroid** [LordSaac/ProgressLottieIGB#1]
Current it is showing default size it is match parent. how i can customize Lottie icon Size.
![size_issue](https://user-images.githubusercontent.com/15724660/51676681-5d0f9500-1ffd-11e9-8fc9-b4ae1c3c43f1.png)

**Comment by LordSaac** [comment]
HI

You try new version released February 1, 2019,
` implementation 'com.jgb.lordsaac.igb.progresslitieigb:progresslottieigb:0.0.2'`

## Kotlin Code

#### Code:  
```
    ProgressLoadingIGB.startLoadingIGB(this){
            message = "Good Morning!" //  Center Message
            srcLottieJson = R.raw.loading_a // Tour Source JSON Lottie
            timer = 10000                   // Time of live for progress.
            hight = 500 // Optional
            width = 500 // Optional

        }
```

## Java Code

####  Code:
```
ProgressLoadingJIGB.startLoadingJIGB(context,R.raw.pork_dance,"Happy New Year 2019...",0,200,200);
``` 

Checked wiki: 

https://github.com/LordSaac/ProgressLottieIGB/wiki 

regards,
