### ISSUE TITLE
Still Same Issue.

### ISSUE THREAD

**Issue by sharibtanweer** [LordSaac/ProgressLottieIGB#6]
Its useless to add close button instead it should be auto cancelable true/false like old progress and in version 1.0.0 its not able to find method in java version i tried all your code it is not implementing IProgressLoadingActions it showing that its not found.

**Comment by LordSaac** [comment]
The method added in the version 1.0.0 is manual, this method the user will active for cancel any process. 
you can see function in java en the next link: https://github.com/LordSaac/ProgressLottieIGB/blob/master/app/src/main/java/com/forms/sti/progresslottieigb/Main2Activity.java 

And do you want will use auto cancel, you coul use the option time `  setup.timer = 0;   // Time of live for progress.`

regards.

**Comment by sharibtanweer** [comment]
This Link Not Working In
implementation 'com.jgb.lordsaac.igb.progresslitieigb:progresslottieigb:1.0.0'
And Also This Link: https://github.com/LordSaac/ProgressLottieIGB/blob/master/app/src/main/java/com/forms/sti/progresslottieigb/Main2Activity.java

**Comment by sharibtanweer** [comment]
I Do Not Need Close Button It Should Be Just Like SetCancelable=true/false And Instead of  setup.timer = 0; Also.

**Comment by LordSaac** [comment]
You can use  `setup.timer´` for declarete a time life for loading , so if you want cancel loading in your any process  use `ProgressLoadingJIGB.finishLoadingJIGB(context);`  , please read to all documentation in page. 



Regards,

**Comment by LordSaac** [comment]
Hello
I see error in the version 1.0.0, but i fixed in this version: 1.0.1
implementation 'com.jgb.lordsaac.igb.progresslitieigb: progresslottieigb: 1.0.1'

Thanks for you observations! 

Regards,
