### ISSUE TITLE
Json Loder Color Change Issue And Close Button Tint Color Change Issue.

### ISSUE THREAD

**Issue by sharibtanweer** [LordSaac/ProgressLottieIGB#7]
How to change setup.srcLottieJson = R.raw.loading; // whatever loder progress color change and close button tint color change?

Thanks and Regard

**Comment by LordSaac** [comment]
Hello, 

For moment don t exist the option change color for this code `setup.srcLottieJson` , but you can edit your resource lottie json in your page [Lottie page]( https://lottiefiles.com/14503-sunset-sunrise-animation).

Also can change the color for button cancel using ` cancelButtonColor = R.color.colorPrimary ` and you can add any color for you button also you can add button customizable with the next code` cancelButtonBackground = R.drawable.ic_launcher_background ` but i recommened with use backgrounds type xml. 

Regards,
