### ISSUE TITLE
MavenCentrall Support?

### ISSUE THREAD

**Issue by fkocak2505** [LordSaac/ProgressLottieIGB#8]
Hi, 
jCenter() will stop in 1 Februray 2022. This library will move to mavencentrall?

**Comment by LordSaac** [comment]
Hi, 

Yes this library migrate to mavencentall before 2022. 

@fkocak2505

**Comment by LordSaac** [comment]
Hello @fkocak2505  

* Add the JitPack repository to your project's build.gradle file

```

	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

* Add the dependency in your app's build.gradle file

```
    
    dependencies {
	        implementation 'com.github.LordSaac:ProgressLottieIGB:v1.0.2'
	}
    
```

Regards
